### ISSUE TITLE
Simulation error if first line of recorded file does not contain a MarketDefinition

### ISSUE THREAD

**Issue by derek-cl** [betcode-org/flumine#729]
A small number of my self-recorded market data files for tennis do not have a 'MarketDefinition' in the first row of data, causing the function utils.get_file_md() to throw an exception:

> TypeError: MarketDefinition.__init__() missing 22 required positional arguments: 'betDelay', 'bettingType', 'bspMarket', 'bspReconciled', 'complete', 'crossMatching', 'discountAllowed', 'eventId', 'eventTypeId', 'inPlay', 'marketBaseRate', 'marketTime', 'numberOfActiveRunners', 'numberOfWinners', 'persistenceEnabled', 'regulators', 'runnersVoidable', 'status', 'timezone', 'turnInPlayEnabled', 'version', and 'runners'

**Comment by liampauling** [comment]
Got an example file?

**Comment by derek-cl** [comment]
Here's an example file. Have been working on a fix but it's not as straightforward as I thought.

[1.210223229.gz](https://github.com/betcode-org/flumine/files/13673598/1.210223229.gz)

**Comment by liampauling** [comment]
How has this been recorded as it would not have come from the stream like this

**Comment by derek-cl** [comment]
I have a market recorder set up, based on the example s3 recorder, but I only have 17 example markets where this condition happens, and only for Tennis. I can't explain how this happened, will try and find a common cause.

**Comment by liampauling** [comment]
Ok but this isn't a problem with the simulation engine, its the data being provided.
